default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dev_user
  password: password
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: sample_db_0529_development

test:
  <<: *default
  database: sample_db_0529_test

production:
  <<: *default
  database: sample_db_0529_production
